def curl(cookies):
	return("curl -L 'https://www.united.com/ual/en/us/flight-search/book-a-flight' -H 'Cookie:  "
		+ cookies +
		"""' -H 'Origin: https://www.united.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: https://www.united.com/ual/en/us' -H 'Connection: keep-alive'  --data 'search=&FareTypes=lf&hdnMaxAllowedTravelersCount=9&SearchTypeMain=oneWay&autoCompAirportText=See+full+airport+list&clearHisText=Clear+history&recentsearchLazyload=True&recentSearchSubmit=False&recentsearchTripCloning=True&Origin=SFO&Destination=AUS&Flexible=false&CorporateBooking=false&DepartDate=May+22%2C+2018&ReturnDate=&flexMonth=11%2F26%2F2017&tripLength=6&NumOfAdults=1&NumOfSeniors=0&NumOfChildren04=0&NumOfChildren03=0&NumOfChildren02=0&NumOfChildren01=0&NumOfInfants=0&NumOfLapInfants=0&cabinType=econ&awardCabinType=awardEcon&AwardTravel=false&NonStopOnly=false' --compressed""")


def curl2(cookies, cart_id):
	part1 = """curl 'https://www.united.com/ual/en/us/flight-search/book-a-flight/flightshopping/getflightresults/rev' -H 'Cookie: """
	part2 = """' -H 'Origin: https://www.united.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,fr;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'UASessionTabId: 600de959-061c-4144-b552-92256b34658f' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://www.united.com/ual/en/us/flight-search/book-a-flight/results/rev?f=SFO&t=SAN&d=2018-01-06&tt=1&sc=7&px=2&taxng=1&idx=1' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary '{"Revise":false,"UnaccompaniedMinorDisclamer":false,"IsManualUpsellFromBasicEconomy":false,"ConfirmationID":null,"searchTypeMain":"oneWay","realSearchTypeMain":"oneWay","Origin":"SFO","Destination":"SAN","DepartDate":"Jan 06, 2018","ReturnDate":"Jan 06, 2018","awardTravel":false,"MaxTrips":null,"numberOfTravelers":1,"numOfAdults":1,"numOfSeniors":0,"numOfChildren04":0,"numOfChildren03":0,"numOfChildren02":0,"numOfChildren01":0,"numOfInfants":0,"numOfLapInfants":0,"travelerCount":1,"revisedTravelerKeys":null,"revisedTravelers":null,"OriginalReservation":null,"RiskFreePolicy":null,"IsUnAccompaniedMinor":false,"MilitaryTravelType":null,"MilitaryOrGovernmentPersonnelStateCode":null,"tripLength":0,"IsParallelFareWheelCallEnabled":false,"flexMonth":null,"flexMonth2":null,"SortType":null,"cboMiles":null,"cboMiles2":null,"Trips":[{"BBXCellIdSelected":null,"BBXSession":null,"BBXSolutionSetId":null,"DestinationAll":false,"returnARC":null,"connections":null,"nonStopOnly":false,"nonStop":true,"oneStop":true,"twoPlusStop":true,"ChangeType":0,"DepartDate":"Jan 06, 2018","ReturnDate":null,"PetIsTraveling":false,"PreferredTime":"","PreferredTimeReturn":null,"Destination":"SAN","Index":1,"Origin":"SFO","Selected":false,"NonStopMarket":true,"FormatedDepartDate":"Sat, Jan 06, 2018","OriginCorrection":null,"DestinationCorrection":null,"OriginAll":false,"Flights":null,"SelectedFlights":null,"OriginTriggeredAirport":false,"DestinationTriggeredAirport":false,"StopCount":1,"HasNonStopFlights":false,"Ignored":false,"Sequence":0}],"nonStopOnly":0,"CalendarOnly":false,"InitialShop":true,"IsSearchInjection":false,"CartId":" """
	part3 = """","CellIdSelected":null,"BBXSession":null,"SolutionSetId":null,"SimpleSearch":true,"RequeryForUpsell":false,"RequeryForPOSChange":false,"YBMAlternateService":false,"ShowClassOfServiceListPreference":false,"SelectableUpgradesOriginal":null,"RegionalPremierUpgradeBalance":0,"GlobalPremierUpgradeBalance":0,"RegionalPremierUpgrades":null,"GlobalPremierUpgrades":null,"FormattedAccountBalance":null,"GovType":null,"TripTypes":1,"RealTripTypes":1,"flexible":false,"flexibleAward":false,"FlexibleDaysAfter":0,"FlexibleDaysBefore":0,"hiddenPreferredConn":null,"hiddenUnpreferredConn":null,"carrierPref":0,"chkFltOpt":0,"portOx":0,"travelwPet":0,"NumberOfPets":0,"cabinType":0,"cabinSelection":"ECONOMY","awardCabinType":0,"FareTypes":0,"FareWheelOnly":false,"EditSearch":false,"buyUpgrade":0,"offerCode":null,"IsPromo":false,"TVAOfferCodeLastName":null,"ClassofService":null,"UpgradeType":null,"BillingAddressCountryCode":null,"BillingAddressCountryDescription":null,"IsPassPlusFlex":false,"IsPassPlusSecure":false,"IsOffer":false,"IsMeetingWorks":false,"IsValidPromotion":false,"IsCorporate":0,"CalendarDateChange":null,"CoolAwardSpecials":false,"LastResultId":null,"IncludeLmx":false,"NGRP":false,"calendarStops":4,"IsAwardNonStopDisabled":false,"IsWeeklyAwardCalendarEnabled":true,"IsMonthlyAwardCalendarEnabled":true,"AwardCalendarType":0,"IsAwardCalendarEnabled":true,"IsAwardCalendarNonstop":false,"corporateBooking":false,"CorporateDiscountCode":"","IsAutoUpsellFromBasicEconomy":false,"CurrencyDescription":"International POS Cuurency","CurrentTripIndex":0,"LowestNonStopEconomyFare":0,"isReshopPath":false,"HideFarewheel":true}' --compressed"""
	request = part1 + cookies + part2[:-1] + cart_id + part3
	return(request)
